import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      dir={cookies().get("currentLanguage")?.value === "fa" ? "rtl" : "ltr"}
    >
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
