name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Stop
      run: |
        echo "$PASSWORD" | sudo -S docker kill pouria_pouria-blog_1
      env:
        PASSWORD: ${{ secrets.POURIA_USER_PASSWORD }}
    - name: Start
      run: |
        echo "$PASSWORD" | sudo -S docker-compose up -d --build
      env:
        PASSWORD: ${{ secrets.POURIA_USER_PASSWORD }}